=== derekjackson-hbp/Dynamic-Form-Processing-with-PHP/common/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1"> 

<xs:element name="index">
    <xs:complexType>
     <xs:sequence>
         <xs:element name="indexGroup" type="grouping" minOccurs="1" maxOccurs="unbounded"/>
     </xs:sequence>
    </xs:complexType>
    
</xs:element>
    <xs:complexType name="grouping">
        <xs:sequence>
            <xs:element name="entry" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>                
                        <xs:element name="term" type="xs:string"/>
                        <xs:choice>
                        <xs:element name="finders" type="locators"/>
                        <xs:element name="indexGroup" type="grouping"/>
                        </xs:choice>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="locators">
        <xs:sequence>
            <xs:element name="group" maxOccurs="unbounded" minOccurs="1">
   <xs:complexType>
        <xs:sequence>
            <xs:element name="start" type="location"/>
            <xs:element name="end" type="location"/>  
        </xs:sequence>
   </xs:complexType>
    </xs:element>
        </xs:sequence>
    </xs:complexType>
        <xs:complexType name="location">
            <xs:sequence>
                <xs:element name="paragraph" type="xs:string"/>
                <xs:element name="page" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>    

</xs:schema>

=== derekjackson-hbp/Dynamic-Form-Processing-with-PHP/common/test_A.xml
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
<indexGroup>

<entry>
<term>aaa</term>
<finders>
<group>
<start>
<paragraph>ch01.xhtml#p1</paragraph>
<page>1</page>
</start>
<end>
<paragraph>ch01.xhtml#p1</paragraph>
<page>1</page>
</end>
</group>
</finders>
</entry>
</indexGroup>
</index><?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
<indexGroup>

<entry>
<term>aaa</term>
<finders>
<group>
<start>
<paragraph>ch01.xhtml#p1</paragraph>
<page>1</page>
</start>
<end>
<paragraph>ch01.xhtml#p1</paragraph>
<page>1</page>
</end>
</group>
</finders>
</entry>
</indexGroup>
</index>

=== derekjackson-hbp/Dynamic-Form-Processing-with-PHP/index/test_A.xml
<?xml-stylesheet type="text/xsl" href="../common/transform.xsl"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../common/index.xsd">
<indexGroup>

<entry>
<term>amortizing loan</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_91</paragraph>
<page>23</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch0k.xhtml#1</paragraph>
<page>42</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annual percentage rate</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_91</paragraph>
<page>23</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch02.xhtml#p2_111</paragraph>
<page>30</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch03.xhtml#p3_30</paragraph>
<page>42</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity, in buyout offer example</term>
<finders>
<group>
<start>
<paragraph>ch0f.xhtml#2</paragraph>
<page>26</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity, compared with perpetuity</term>
<finders>
<group>
<start>
<paragraph>ch0e.xhtml#3</paragraph>
<page>27</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity, construction of</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_75</paragraph>
<page>21</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity, definition of</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_33</paragraph>
<page>10</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch0e.xhtml#2</paragraph>
<page>21</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch0k.xhtml#3</paragraph>
<page>42</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity, mortgage as</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_90</paragraph>
<page>23</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity, present value derivation for</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_33</paragraph>
<page>10</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch02.xhtml#p2_74</paragraph>
<page>21</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch02.xhtml#p2_81</paragraph>
<page>22</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity factor (PV factor)</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_80</paragraph>
<page>22</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch0k.xhtml#4</paragraph>
<page>42</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>
</indexGroup>
</index>

=== derekjackson-hbp/Dynamic-Form-Processing-with-PHP/storage/test_A1.xml
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>


<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
<indexGroup>
    <entry>
<term>Add</term>
<finders>
<group>
<start>
<paragraph>p1_3</paragraph>
<page>1</page>
</start>
<end>
<paragraph>0</paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>p2_2</paragraph>
<page>4</page>
</start>
<end>
<paragraph>p2_5</paragraph>
<page>5</page>
</end>
</group>
</finders>
    </entry>


<entry>
<term>Anvil</term>
<finders>
<group>
<start>
<paragraph>p2_22</paragraph>
<page>15</page>
</start>
<end>
<paragraph>0</paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>Axe</term>
<finders>
<group>
<start>
<paragraph>p1_4</paragraph>
<page>2</page>
</start>
<end>
<paragraph>p1_6</paragraph>
<page>3</page>
</end>
</group>
<group>
<start>
<paragraph>p2_22</paragraph>
<page>15</page>
</start>
<end>
<paragraph>0</paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>p2_30</paragraph>
<page>22</page>
</start>
<end>
<paragraph>p2_40</paragraph>
<page>24</page>
</end>
</group>
</finders>
</entry>
</indexGroup>
</index>

=== derekjackson-hbp/Dynamic-Form-Processing-with-PHP/index/test.xml
<?xml-stylesheet type="text/xsl" href="../common/transform.xsl"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../common/index.xsd">
<indexGroup>

<entry>
<term>amortizing loan, </term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_9</paragraph>
<page>23</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch0k.xhtml#1</paragraph>
<page>42</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>annuity, present value derivation for</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_33</paragraph>
<page>10</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch02.xhtml#p2_74</paragraph>
<page>21</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
<group>
<start>
<paragraph>ch02.xhtml#p2_81</paragraph>
<page>22</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>
</indexGroup>

<indexGroup>

<entry>
<term>bank loans</term>
<finders>
<group>
<start>
<paragraph>ch01.xhtml#p1_2</paragraph>
<page>3</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>buyout offer example</term>
<finders>
<group>
<start>
<paragraph>ch0f.xhtml#2</paragraph>
<page>26</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>
</indexGroup>
</index><?xml-stylesheet type="text/xsl" href="../common/transform.xsl"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../common/index.xsd">
<indexGroup>

<entry>
<term>amortizing loan</term>
<finders>
<group>
<start>
<paragraph>ch0a.xhtml#pa</paragraph>
<page>a</page>
</start>
<end>
<paragraph></paragraph>
<page>a</page>
</end>
</group>
</finders>
</entry>
</indexGroup>
</index>

=== derekjackson-hbp/Dynamic-Form-Processing-with-PHP/common/final.xml
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../common/index.xsd">
<indexGroup>

<entry>
<term>Award</term>
<finders>
<group>
<start>
<paragraph>ch01.xhtml#p1_1</paragraph>
<page>1</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>

<entry>
<term>Awl</term>
<finders>
<group>
<start>
<paragraph>ch00.xhtml#_kt5</paragraph>
<page>33</page>
</start>
<end>
<paragraph></paragraph>
<page>0</page>
</end>
</group>
</finders>
</entry>
</indexGroup>

 <indexGroup> 

<entry>
<term>Dog</term>
<finders>
<group>
<start>
<paragraph>ch02.xhtml#p2_2</paragraph>
<page>3</page>
</start>
<end>
<paragraph>ch02.xhtml#p2_10</paragraph>
<page>5</page>
</end>
</group>
</finders>
</entry>
</indexGroup>
</index>
